"use client";

import type { Guard, View } from "./management-types";
import PageHeading from "./PageHeading";
import Metric from "./Metric";

function Dashboard({ guards, active, onNavigate }: { guards: Guard[]; active: number; onNavigate: (v: View) => void }) {
  const cards: { icon: string; badge: string; title: string; description: string; action: string; page: View; color: string }[] = [
    { icon: "♙+", badge: "REGISTRATION", title: "Register New Guard", description: "Enroll guards with full profile details, shift assignment, and deployment information.", action: "Open Registration Form", page: "Register Guard", color: "blue" },
    { icon: "♙", badge: "PERSONNEL", title: "Guard Roster & Profiles", description: "Search the active roster, filter by status, and manage guard profiles.", action: "View Guard List", page: "Guard List", color: "blue" },
    { icon: "▣", badge: "OPERATIONS", title: "Daily Attendance Tracker", description: "Mark attendance and review present, absent, and leave records by day.", action: "Open Attendance Sheet", page: "Attendance", color: "green" },
    { icon: "▤", badge: "FINANCE", title: "Invoice & Billing Generator", description: "Create client invoices and keep a searchable billing record.", action: "Create / View Invoices", page: "Invoices", color: "gold" },
  ];
  return <div className="content-wrap"><PageHeading eyebrow="Admin Control Center" title="Welcome back, Admin 👋" subtitle={`${new Date().toLocaleDateString("en-IN", { weekday: "long", day: "numeric", month: "long", year: "numeric" })} · workforce overview`} action={<button className="primary-button" onClick={() => onNavigate("Register Guard")}>＋ &nbsp; Add New Guard</button>} /><section className="summary-row"><Metric label="TOTAL ENROLLED PERSONNEL" value={guards.length} note="Roster count" icon="♙" tone="blue" /><Metric label="ACTIVE DEPLOYMENTS" value={active} note="On duty" icon="♙" tone="green" /><Metric label="INACTIVE / ON LEAVE" value={guards.length - active} note="Standby" icon="♙" tone="red" /></section><div className="section-heading"><div><h2>Management modules</h2><p>Choose an area to manage your security operation.</p></div><span className="live-pill">● SUPABASE CONNECTED</span></div><div className="module-grid">{cards.map(card => <button className="module-card" key={card.title} onClick={() => onNavigate(card.page)}><div className="module-top"><div className={`module-icon ${card.color}`}>{card.icon}</div><span className="module-badge">{card.badge}</span></div><h3>{card.title}</h3><p>{card.description}</p><div className="module-link">{card.action}<span>›</span></div></button>)}</div><div className="storage-note"><span>▤</span><div><strong>Supabase database is active</strong><p>Roster, attendance, and invoices sync through your protected Supabase project.</p></div></div></div>;
}