"use client";

import type { Invoice } from "./management-types";
import PageHeading from "./PageHeading";
import Metric from "./Metric";

export default function InvoicesPage({ invoices, onNew }: { invoices: Invoice[]; onNew: () => void }) {
  const total = invoices.reduce((sum,i) => sum+i.amount,0);
  return <div className="content-wrap"><PageHeading eyebrow="Finance & billing" title="Invoices & Billing" subtitle="Create client invoices and keep a searchable billing record." action={<button className="primary-button" onClick={onNew}>＋ &nbsp; Create Invoice</button>} /><div className="summary-row"><Metric label="TOTAL INVOICES" value={invoices.length} note="All records" icon="▤" tone="blue" /><Metric label="TOTAL BILLING" value={total} note="Invoice value (INR)" icon="₹" tone="green" /><Metric label="PAID INVOICES" value={invoices.filter(i=>i.status==="Paid").length} note="Payment received" icon="✓" tone="gold" /></div><div className="table-wrap"><table><thead><tr><th>INVOICE ID</th><th>CLIENT</th><th>DESCRIPTION</th><th>ISSUE DATE</th><th>AMOUNT</th><th>STATUS</th><th>ACTIONS</th></tr></thead><tbody>{invoices.map(invoice => <tr key={invoice.id}><td><span className="id-tag">{invoice.id}</span></td><td><strong>{invoice.client}</strong></td><td>{invoice.description}</td><td>{new Date(`${invoice.date}T00:00:00`).toLocaleDateString("en-IN")}</td><td>₹{invoice.amount.toLocaleString("en-IN")}</td><td><span className={`status ${invoice.status.toLowerCase()}`}>{invoice.status}</span></td><td><button className="text-action" onClick={() => window.print()}>Print</button></td></tr>)}{!invoices.length && <tr><td colSpan={7} className="empty-state"><span className="empty-icon">▤</span><strong>No invoices yet</strong><small>Create your first client invoice to get started.</small><button className="primary-button" onClick={onNew}>＋ &nbsp; Create Invoice</button></td></tr>}</tbody></table></div></div>;
}