"use client";

import { useEffect, useRef, useState } from "react";
import Image from "next/image";
import type { Guard } from "./management-types";
import { today } from "./management-utils";
import PageHeading from "./PageHeading";
import Field from "./Field";

export default function RegisterGuard({ onSave, onCancel }: { onSave: (g: Guard) => Promise<void>; onCancel: () => void }) {
  const [photo, setPhoto] = useState(""); const [workType, setWorkType] = useState("Permanent"); const [shift, setShift] = useState("Day Shift"); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const videoRef = useRef<HTMLVideoElement>(null); const cameraStreamRef = useRef<MediaStream | null>(null); const fileInputRef = useRef<HTMLInputElement>(null); const [cameraOpen, setCameraOpen] = useState(false);
  const progress = 14;
  const uploadPhoto = (file?: File) => { if (!file) return; if (!file.type.startsWith("image/")) { setError("Choose an image file."); return; } const image = new window.Image(); image.onload = () => { const canvas = document.createElement("canvas"); const scale = Math.min(1, 1500 / Math.max(image.width, image.height)); canvas.width = Math.round(image.width * scale); canvas.height = Math.round(image.height * scale); canvas.getContext("2d")?.drawImage(image, 0, 0, canvas.width, canvas.height); setPhoto(canvas.toDataURL("image/jpeg", 0.82)); }; image.onerror = () => setError("Could not read the selected photo."); image.src = URL.createObjectURL(file); };
  const stopCamera = () => { cameraStreamRef.current?.getTracks().forEach(track => track.stop()); cameraStreamRef.current = null; setCameraOpen(false); };
  const openCamera = async () => { setError(""); if (!navigator.mediaDevices?.getUserMedia) { setError("Live camera needs HTTPS or localhost. Open this site in a supported browser."); return; } try { cameraStreamRef.current = await navigator.mediaDevices.getUserMedia({ video: { facingMode: { ideal: "environment" } }, audio: false }); setCameraOpen(true); } catch (cause) { const cameraError = cause instanceof Error ? cause : null; setError(cameraError?.name === "NotAllowedError" ? "Camera permission is blocked. Allow camera access in your browser settings and try again." : cameraError?.name === "NotFoundError" ? "No camera was found on this device." : "Could not open the camera. Check that it is connected and not being used by another app."); } };
  const captureCameraPhoto = () => { const video = videoRef.current; if (!video || !video.videoWidth) { setError("Camera is starting. Try again in a moment."); return; } const canvas = document.createElement("canvas"); const scale = Math.min(1, 1500 / Math.max(video.videoWidth, video.videoHeight)); canvas.width = Math.round(video.videoWidth * scale); canvas.height = Math.round(video.videoHeight * scale); canvas.getContext("2d")?.drawImage(video, 0, 0, canvas.width, canvas.height); setPhoto(canvas.toDataURL("image/jpeg", 0.82)); stopCamera(); };
  useEffect(() => { if (cameraOpen && videoRef.current && cameraStreamRef.current) { videoRef.current.srcObject = cameraStreamRef.current; void videoRef.current.play().catch(() => {}); } }, [cameraOpen]);
  useEffect(() => () => { cameraStreamRef.current?.getTracks().forEach(track => track.stop()); }, []);
  return <div className="content-wrap form-page"><PageHeading eyebrow="Personal Enrollment" title="Security Guard Registration" subtitle="Fill in the details below. The guard profile will be saved to Supabase." /><form onSubmit={async e => { e.preventDefault(); setError(""); setSaving(true); const data = new FormData(e.currentTarget); const id = `GRD${crypto.randomUUID().slice(0,7).toUpperCase()}`; const name=String(data.get("name")); try { await onSave({ id, name, phone: String(data.get("phone")), email: String(data.get("email")), aadhaar: String(data.get("aadhaar")), gender: String(data.get("gender")), dob: String(data.get("dob")), address: String(data.get("address")), designation: String(data.get("designation")), site: String(data.get("site")), salary: Number(data.get("salary")), joinDate: String(data.get("joinDate")), status: "Active", shift, workType, photo: photo || undefined }); } catch (cause) { setError(cause instanceof Error ? cause.message : "Guard record could not be saved."); } finally { setSaving(false); } }}>
    <div className="form-progress"><div><strong>Form Readiness</strong><span>{progress}%</span></div><div className="progress-track"><i style={{ width: `${progress}%` }} /></div><small>Complete all required fields</small></div>
    <section className="form-section"><div className="form-section-title"><h2><span>1</span>Personal & Identification Information</h2><small>* Indicates mandatory field</small></div><div className="personal-layout"><div className="photo-column"><div className="photo-preview">{photo ? <Image src={photo} alt="Guard preview" width={200} height={200} unoptimized /> : <span><i>♙</i>Photo preview</span>}</div><input ref={fileInputRef} className="photo-input-hidden" type="file" accept="image/*" onChange={e => uploadPhoto(e.target.files?.[0])} /><button type="button" className="upload-button" onClick={() => void openCamera()}>📷 &nbsp; Take Photo</button><button type="button" className="upload-button upload-button-secondary" onClick={() => fileInputRef.current?.click()}>▧ &nbsp; Upload from File</button><small>Camera preview or choose an image file.</small></div><div className="form-fields"><div className="field-grid"><Field label="Full Name" name="name" placeholder="e.g. Ramesh Kumar Sharma" required /><Field label="Contact Number (Phone)" name="phone" placeholder="+91 9876543210" required type="tel" pattern="[+0-9 ()-]{10,18}" /><Field label="Email Address" name="email" placeholder="guard@airavatsecurity.in" type="email" /><Field label="Date of Birth" name="dob" required type="date" /><Field label="Aadhaar Card Number" name="aadhaar" placeholder="XXXX XXXX XXXX" required pattern="[0-9Xx ]{12,16}" /><label className="field"><span>Gender <b>*</b></span><select name="gender" required defaultValue=""><option value="" disabled>Select gender</option><option>Male</option><option>Female</option><option>Other</option></select></label></div></div></div><div className="field full-field"><span>Residential Address <b>*</b></span><input name="address" required placeholder="e.g. Plot 12, Khodiyar Colony, Jamnagar, Gujarat - 361006" /></div></section>
    <section className="form-section"><div className="form-section-title"><h2><span>2</span>Employment, Shift & Payment Details</h2><small>Operations & deployment</small></div><div className="field-grid employment-grid"><fieldset className="choice-field"><legend>Work Type <b>*</b></legend><div className="choice-row">{["Permanent", "Temporary"].map(w => <label className={`choice-card ${workType === w ? "choice-selected" : ""}`} key={w}><input type="radio" checked={workType === w} onChange={() => setWorkType(w)} /> <strong>{w}</strong><small>{w === "Permanent" ? "Full-time roster guard" : "Short-term / relief duty"}</small></label>)}</div></fieldset><fieldset className="choice-field"><legend>Preferred Shift <b>*</b></legend><div className="choice-row">{["Day Shift", "Night Shift", "Rotational"].map((s,i) => <label className={`shift-card ${shift === s ? "choice-selected" : ""}`} key={s}><input type="radio" checked={shift === s} onChange={() => setShift(s)} /><strong>{["☀", "☾", "▣"][i]}</strong><span>{s}</span><small>{["08:00 – 20:00", "20:00 – 08:00", "Any shift"][i]}</small></label>)}</div></fieldset><label className="field"><span>Designation / Role <b>*</b></span><select name="designation"><option>Security Guard</option><option>Head Guard</option><option>CCTV Operator</option><option>Supervisor</option><option>Patrolling Officer</option></select></label><Field label="Client Site Deployed" name="site" placeholder="Select or type a client site" /><Field label="Monthly Salary (INR)" name="salary" type="number" min="1" placeholder="18000" required /><Field label="Joining Date" name="joinDate" type="date" required defaultValue={today()} /></div><label className="field full-field"><span>Remarks & Special Notes</span><textarea name="remarks" placeholder="Any special instructions, uniform size, background verification notes…" /></label></section>
    {error && <p className="error-text">{error}</p>}
    <div className="form-actions"><button className="secondary-button" type="button" onClick={onCancel}>← &nbsp; Cancel & Back to Guard Roster</button><div><button className="secondary-button" type="reset" onClick={() => setPhoto("")}>Reset Form</button><button className="primary-button" type="submit" disabled={saving}>{saving ? "Saving to Supabase…" : "Enroll & Save Guard Record →"}</button></div></div>
  </form>{cameraOpen && <div className="camera-backdrop" role="presentation" onMouseDown={event => { if (event.target === event.currentTarget) stopCamera(); }}><section className="camera-dialog" role="dialog" aria-modal="true" aria-labelledby="camera-title"><div className="camera-dialog-heading"><h2 id="camera-title">Take guard photo</h2><button type="button" className="camera-close" onClick={stopCamera} aria-label="Close camera">×</button></div><video ref={videoRef} className="camera-video" autoPlay playsInline muted /><p>Position the guard in the frame, then capture.</p><div className="camera-actions"><button type="button" className="secondary-button" onClick={stopCamera}>Cancel</button><button type="button" className="primary-button" onClick={captureCameraPhoto}>Capture Photo</button></div></section></div>}</div>;
}