"use client";

import type { Guard } from "./management-types";
import PageHeading from "./PageHeading";
import Metric from "./Metric";
import GuardPhoto from "./GuardPhoto";

export default function Roster({ guards, allCount, active, query, setQuery, filter, setFilter, onAdd, onSelect, onToggle, onDelete }: { guards: Guard[]; allCount: number; active: number; query: string; setQuery: (s: string) => void; filter: string; setFilter: (s: string) => void; onAdd: () => void; onSelect: (g: Guard) => void; onToggle: (g: Guard) => void; onDelete: (g: Guard) => void }) {
  return <div className="content-wrap"><PageHeading eyebrow="Personnel directory" title="Security Personnel Roster" subtitle={`${allCount} total enrolled guards · ${active} on active deployment`} action={<button className="primary-button" onClick={onAdd}>＋ &nbsp; Enroll New Guard</button>} /><section className="summary-row roster-stats"><Metric label="TOTAL ENROLLED PERSONNEL" value={allCount} note="Roster count" icon="♙" tone="blue" /><Metric label="ACTIVE DEPLOYMENTS" value={active} note="On duty" icon="♙" tone="green" /><Metric label="INACTIVE / ON LEAVE" value={allCount-active} note="Standby" icon="♙" tone="red" /></section><div className="roster-toolbar"><div className="search-wrap"><span>⌕</span><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search name, guard ID, site, designation, phone, or Aadhaar…" /></div><div className="filter-buttons">{["All", "Active", "Inactive"].map(x => <button key={x} onClick={() => setFilter(x)} className={filter === x ? "selected-filter" : ""}>{x}</button>)}</div></div><div className="table-wrap"><table><thead><tr><th>GUARD ID</th><th>PHOTO & NAME</th><th>CONTACT</th><th>DESIGNATION</th><th>SITE DEPLOYED</th><th>SALARY</th><th>JOIN DATE</th><th>STATUS</th><th>ACTIONS</th></tr></thead><tbody>{guards.map(g => <tr key={g.id}><td><span className="id-tag">{g.id}</span></td><td><button className="person-cell" onClick={() => onSelect(g)}><GuardPhoto path={g.photo} label={g.name} className="avatar" /><span><strong>{g.name}</strong><small>{g.gender} · DOB: {g.dob ? new Date(`${g.dob}T00:00:00`).toLocaleDateString("en-IN") : "—"}</small></span></button></td><td>{g.phone}<small className="cell-sub">{g.email || "—"}</small></td><td><span className="designation-tag">{g.designation}</span></td><td className="site-cell">{g.site || "Unassigned"}</td><td>₹{g.salary.toLocaleString("en-IN")}<small className="cell-sub">/mo</small></td><td>{new Date(`${g.joinDate}T00:00:00`).toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" })}</td><td><span className={`status ${g.status.toLowerCase()}`}>{g.status}</span></td><td><div className="actions"><button title="View profile" onClick={() => onSelect(g)}>◉</button><button title={g.status === "Active" ? "Mark inactive" : "Activate"} onClick={() => onToggle(g)}>{g.status === "Active" ? "⏸" : "▶"}</button><button title="Delete" className="delete-action" onClick={() => onDelete(g)}>⌫</button></div></td></tr>)}{!guards.length && <tr><td colSpan={9} className="empty-state">No guards found. Try a different search or register a guard.</td></tr>}</tbody></table></div><p className="table-foot">Showing {guards.length} of {allCount} guards · Select a guard name to view the complete profile</p></div>;
}